const fs = require('fs');
const path = require('path');

const localesPath = path.join(__dirname, '../src/locales');

const enFile = path.join(localesPath, 'en.json');
const taFile = path.join(localesPath, 'ta.json');
const urFile = path.join(localesPath, 'ur.json');

const en = JSON.parse(fs.readFileSync(enFile, 'utf8'));
const ta = JSON.parse(fs.readFileSync(taFile, 'utf8'));
const ur = JSON.parse(fs.readFileSync(urFile, 'utf8'));

const newEn = {
  footer: {
    brandDesc: "A place of intellectual clarity and spiritual repose, cultivating minds in a vibrant environment.",
    quickLinks: "Quick Links",
    noticeBoard: "Notice Board",
    scholarships: "Scholarships",
    legal: "Legal",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    connect: "Connect",
    copyright: "© 2024 Dawoodiya Masjid & Madrasah. All rights reserved."
  },
  about: {
    tab_history: "History",
    tab_vision: "Vision & Mission",
    tab_professors: "Professors",
    tab_alumni: "Alumni",
    title: "About Us",
    needAssistance: "Need Assistance?",
    contactAdmin: "Contact our administration office for any inquiries regarding the institute's background.",
    contactUs: "Contact Us",
    history_title: "Our Blessed History",
    history_subtitle: "A centenarian legacy of faith and scholarship.",
    history_desc: "Established with a profound commitment to the preservation and dissemination of sacred knowledge, our institution has stood as a beacon of light for decades. We are rooted in the classical tradition, yet fully aware of the contemporary needs of the Ummah.",
    history_q1_title: "Foundation of the Main Sanctum",
    history_q1_desc: "The first cornerstone was laid by esteemed scholars and luminaries of the era. The initial cohort consisted of just 15 dedicated students seeking sacred knowledge.",
    history_q2_title: "Curriculum Formalization",
    history_q2_desc: "A rigorous syllabus integrating traditional Dars-e-Nizami with modern pedagogical frameworks was officially adopted, setting a new standard for Islamic institutes.",
    history_q3_title: "Inauguration of the Great Library",
    history_q3_desc: "The expansive library storing thousands of historical volumes and rare manuscripts was opened to the public and researchers worldwide.",
    history_q4_title: "Digital Transformation & Global Reach",
    history_q4_desc: "Launching online programs and virtual classrooms, allowing students from across the globe to benefit from our esteemed faculty.",
    history_quote: "\"We do not merely teach books; we strive to forge characters imbued with the prophetic light, capable of navigating the darkest of times.\"",
    history_quote_author: "— Founding Shaykh",
    vision_title: "Vision & Mission",
    vision_the_vision: "The Vision",
    vision_the_vision_desc: "To be a global pillar of Islamic scholarship, radiating divine guidance and nurturing minds that bridge eternal truth with contemporary challenges. We envision a society transformed by individuals who act as living embodiments of prophetic virtues.",
    vision_the_mission: "The Mission",
    vision_the_mission_desc: "To cultivate a profound understanding of Deen through rigorous academic discipline, spiritual tarbiyah, and the preservation of sacred texts. We commit to providing an environment where faith and reason harmonize perfectly.",
    vision_core_values: "Core Values",
    val1_title: "Ikhlas (Sincerity)",
    val1_desc: "Doing all actions purely for the sake of the Divine.",
    val2_title: "Adab (Refinement)",
    val2_desc: "Cultivating impeccable manners in all interactions.",
    val3_title: "Taqwa (Consciousness)",
    val3_desc: "Maintaining an ever-present awareness of the Creator.",
    val4_title: "Khidmah (Service)",
    val4_desc: "Serving humanity with humility and profound empathy.",
    val5_title: "Ihsan (Excellence)",
    val5_desc: "Striving for perfection in both worship and worldly duties.",
    val6_title: "Sanad (Chain)",
    val6_desc: "Preserving the unbroken chain of transmission.",
    prof_title: "Our Distinguished Faculty",
    prof_subtitle: "Learn from inheritors of the prophetic legacy. Our scholars bring decades of traditional study combined with deep contextual awareness.",
    prof1_role: "Head of Hadith Sciences",
    prof2_role: "Chief of Fiqh & Fatwa",
    prof3_role: "Tasawwuf & Spirituality",
    prof4_role: "Arabic Rhetoric",
    prof_exp_label: "Experience",
    prof_desc: "A renowned expert locally and internationally, dedicated to grounding students in foundational texts with an eye toward practical application.",
    alumni_title: "Global Alumni Network",
    alumni_subtitle: "Graduates of Dawoodiya are illuminating communities across the globe. From community leaders and imams to professionals and academics, our alumni carry the torch of sacred knowledge wherever they go.",
    stat1: "Total Graduates",
    stat2: "Countries Reached",
    stat3: "Published Authors",
    stat4: "Active Imams",
    alumni_contributions: "Notable Contributions",
    alumni_pioneer: "Community Pioneer",
    alumni_class: "Class of",
    alumni_desc: "Established a thriving inner-city youth center bridging traditional Islamic studies with robust social services, deeply impacting thousands of young lives."
  }
};

const newTa = {
  footer: {
    brandDesc: "அறிவுத் தெளிவு மற்றும் ஆன்மீக ஓய்வுக்கான இடம், துடிப்பான சூழலில் மனங்களை வளர்க்கிறது.",
    quickLinks: "முக்கிய இணைப்புகள்",
    noticeBoard: "அறிவிப்பு பலகை",
    scholarships: "உதவித்தொகை",
    legal: "சட்டபூர்வமானது",
    privacy: "தனியுரிமைக் கொள்கை",
    terms: "சேவை விதிமுறைகள்",
    connect: "தொடர்பில் இருங்கள்",
    copyright: "© 2024 தாவூதியா மஸ்ஜித் மற்றும் மதரஸா. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."
  },
  about: {
    tab_history: "வரலாறு",
    tab_vision: "நோக்கம் மற்றும் குறிக்கோள்",
    tab_professors: "பேராசிரியர்கள்",
    tab_alumni: "பழைய மாணவர்கள்",
    title: "எங்களை பற்றி",
    needAssistance: "உதவி தேவையா?",
    contactAdmin: "நிறுவனத்தின் பின்னணி குறித்த எந்தவொரு விசாரணைக்கும் எங்கள் நிர்வாக அலுவலகத்தை தொடர்பு கொள்ளவும்.",
    contactUs: "தொடர்புக்கு",
    history_title: "எங்கள் ஆசீர்வதிக்கப்பட்ட வரலாறு",
    history_subtitle: "நம்பிக்கை மற்றும் அறிவாற்றலின் நூறாண்டு பாரம்பரியம்.",
    history_desc: "புனித அறிவைப் பாதுகாத்தல் மற்றும் பரப்புதல் என்ற ஆழமான அர்ப்பணிப்புடன் நிறுவப்பட்ட எங்கள் நிறுவனம் பல தசாப்தங்களாக ஒளியின் கலங்கரை விளக்கமாக நின்றுள்ளது. நாங்கள் பாரம்பரிய மரபில் வேரூன்றியுள்ளோம், அதே சமயம் சமூகத்தின் சமகால தேவைகளை முழுமையாக அறிவோம்.",
    history_q1_title: "பிரதான வளாகத்தின் அடித்தளம்",
    history_q1_desc: "முதல் அடிக்கல் மதிப்பிற்குரிய அறிஞர்கள் மற்றும் যুগের ஒளியாளர்களால் நாட்டப்பட்டது. ஆரம்ப தொகுதி புனித அறிவைத் தேடும் வெறும் 15 அர்ப்பணிப்புள்ள மாணவர்களைக் கொண்டிருந்தது.",
    history_q2_title: "பாடத்திட்ட முறையாக்கம்",
    history_q2_desc: "நவீன கல்வி கற்பித்தல் கட்டமைப்புடன் பாரம்பரிய தர்ஸ்-இ-நிஜாமியை ஒருங்கிணைக்கும் ஒரு கடுமையான பாடத்திட்டம் அதிகாரப்பூர்வமாக ஏற்றுக்கொள்ளப்பட்டது, இது இஸ்லாமிய நிறுவனங்களுக்கு ஒரு புதிய தரத்தை அமைத்தது.",
    history_q3_title: "பெரிய நூலகத்தின் திறப்பு விழா",
    history_q3_desc: "ஆயிரக்கணக்கான வரலாற்று தொகுதிகள் மற்றும் அரிய கையெழுத்துப் பிரதிகளை சேமித்து வைக்கும் விரிவான நூலகம் பொதுமக்கள் மற்றும் ஆராய்ச்சியாளர்களுக்காக திறக்கப்பட்டது.",
    history_q4_title: "டிஜிட்டல் மாற்றம் மற்றும் உலகளாவிய வீச்சு",
    history_q4_desc: "உலகெங்கிலும் உள்ள மாணவர்கள் எங்கள் மதிப்பிற்குரிய ஆசிரியர்களிடமிருந்து பயனடைய அனுமதிக்கும் வகையில் ஆன்லைன் திட்டங்கள் மற்றும் மெய்நிகர் வகுப்பறைகளை அறிமுகப்படுத்துதல்.",
    history_quote: "\"நாங்கள் புத்தகங்களை மட்டும் கற்பிப்பதில்லை; இருண்ட காலங்களில் கூட வழிகாட்டக்கூடிய தீர்க்கதரிசன ஒளியால் ஈர்க்கப்பட்ட குணங்களை உருவாக்க முயற்சிக்கிறோம்.\"",
    history_quote_author: "— நிறுவனர் ஷேக்",
    vision_title: "நோக்கம் மற்றும் குறிக்கோள்",
    vision_the_vision: "நோக்கம்",
    vision_the_vision_desc: "இஸ்லாமிய புலமையின் உலகளாவிய தூணாக இருக்க, தெய்வீக வழிகாட்டுதலைப் பரப்பி, நித்திய உண்மையை சமகால சவால்களுடன் இணைக்கும் மனங்களை வளர்ப்பது. தீர்க்கதரிசன நற்பண்புகளின் வாழும் உருவகமாக செயல்படும் தனிநபர்களால் மாற்றப்பட்ட ஒரு சமூகத்தை நாங்கள் கற்பனை செய்கிறோம்.",
    vision_the_mission: "குறிக்கோள்",
    vision_the_mission_desc: "கடுமையான கல்வி ஒழுக்கம், ஆன்மீக தர்பியா மற்றும் புனித நூல்களின் பாதுகாப்பு மூலம் மார்க்கத்தின் ஆழமான புரிதலை வளர்ப்பது. நம்பிக்கையும் பகுத்தறிவும் கச்சிதமாக இணையும் சூழலை வழங்க நாங்கள் கடமைப்பட்டுள்ளோம்.",
    vision_core_values: "முக்கிய மதிப்புகள்",
    val1_title: "இக்லாஸ் (தூய்மை)",
    val1_desc: "எல்லா செயல்களையும் இறைவனுக்காக மட்டுமே செய்வது.",
    val2_title: "அதாப் (பண்பாடு)",
    val2_desc: "அனைத்து தொடர்புகளிலும் குறைவற்ற நற்பண்புகளை வளர்ப்பது.",
    val3_title: "தக்வா (இறையச்சம்)",
    val3_desc: "படைத்தவனைப் பற்றிய எப்போதும் இருக்கும் விழிப்புணர்வைப் பேணுதல்.",
    val4_title: "கித்மா (சேவை)",
    val4_desc: "பணிவு மற்றும் ஆழமான பச்சாதாபத்துடன் மனிதகுலத்திற்கு சேவை செய்வது.",
    val5_title: "இஹ்ஸான் (சிறப்பு)",
    val5_desc: "வழிபாடு மற்றும் உலக கடமைகள் இரண்டிலும் பரிபூரணத்திற்காக பாடுபடுவது.",
    val6_title: "ஸனத் (சங்கிலி)",
    val6_desc: "அறிவின் பிரிக்கப்படாத சங்கிலியைப் பாதுகாத்தல்.",
    prof_title: "எங்கள் புகழ்பெற்ற ஆசிரியர்கள்",
    prof_subtitle: "தீர்க்கதரிசன மரபின் வாரிசுகளிடமிருந்து கற்றுக்கொள்ளுங்கள். எங்கள் அறிஞர்கள் பல தசாப்த கால பாரம்பரிய ஆய்வை ஆழமான சூழ்நிலை விழிப்புணர்வுடன் கொண்டு வருகிறார்கள்.",
    prof1_role: "ஹதீஸ் அறிவியலின் தலைவர்",
    prof2_role: "ஃபிக்ஹ் & ஃபத்வாவின் தலைவர்",
    prof3_role: "தஸவ்வுஃப் & ஆன்மீகம்",
    prof4_role: "அரபு சொல்லாட்சி",
    prof_exp_label: "அனுபவம்",
    prof_desc: "உள்ளூர் மற்றும் சர்வதேச அளவில் புகழ்பெற்ற நிபுணர், நடைமுறைப் பயன்பாட்டைக் கருத்தில் கொண்டு மாணவர்களை அடிப்படை நூல்களில் நிலைநிறுத்துவதற்கு அர்ப்பணிக்கப்பட்டவர்.",
    alumni_title: "உலகளாவிய முன்னாள் மாணவர் வலைப்பின்னல்",
    alumni_subtitle: "தாவூதியாவின் பட்டதாரிகள் உலகெங்கிலும் உள்ள சமூகங்களை ஒளிரச் செய்கிறார்கள். சமூகத் தலைவர்கள் மற்றும் இமாம்கள் முதல் தொழில் வல்லுநர்கள் மற்றும் கல்வியாளர்கள் வரை, எங்கள் முன்னாள் மாணவர்கள் எங்கு சென்றாலும் புனித அறிவின் ஜோதியை எடுத்துச் செல்கிறார்கள்.",
    stat1: "மொத்த பட்டதாரிகள்",
    stat2: "சென்றடைந்த நாடுகள்",
    stat3: "வெளியிட்ட ஆசிரியர்கள்",
    stat4: "செயலில் உள்ள இமாம்கள்",
    alumni_contributions: "குறிப்பிடத்தக்க பங்களிப்புகள்",
    alumni_pioneer: "சமூக முன்னோடி",
    alumni_class: "படித்த ஆண்டு",
    alumni_desc: "பாரம்பரிய இஸ்லாமிய ஆய்வுகளை வலுவான சமூக சேவைகளுடன் இணைக்கும் ஒரு துடிப்பான இளைஞர் மையத்தை நிறுவியுள்ளார், இது ஆயிரக்கணக்கான இளம் உயிர்களை ஆழமாக பாதிக்கிறது."
  }
};

const newUr = {
  footer: {
    brandDesc: "فکری وضاحت اور روحانی سکون کی جگہ، جو ایک متحرک ماحول میں ذہنوں کی پرورش کرتی ہے۔",
    quickLinks: "فوری لنکس",
    noticeBoard: "نوٹس بورڈ",
    scholarships: "وظائف",
    legal: "قانونی",
    privacy: "پرائیویسی پالیسی",
    terms: "سروس کی شرائط",
    connect: "رابطہ کریں",
    copyright: "© 2024 داؤدیہ مسجد اور مدرسہ۔ جملہ حقوق محفوظ ہیں۔"
  },
  about: {
    tab_history: "تاریخ",
    tab_vision: "مقصد اور مشن",
    tab_professors: "اساتذہ",
    tab_alumni: "سابق طلباء",
    title: "ہمارے بارے میں",
    needAssistance: "مدد چاہیے؟",
    contactAdmin: "ادارے کے پس منظر کے حوالے سے کسی بھی پوچھ گچھ کے لیے ہمارے انتظامی دفتر سے رابطہ کریں۔",
    contactUs: "رابطہ کریں",
    history_title: "ہماری مبارک تاریخ",
    history_subtitle: "ایمان اور علم کی ایک صدی کی وراثت۔",
    history_desc: "مقدس علم کے تحفظ اور پھیلاؤ کے گہرے عزم کے ساتھ قائم کیا گیا، ہمارا ادارہ دہائیوں سے روشنی کے مینار کے طور پر کھڑا ہے۔ ہم کلاسیکی روایت میں جڑے ہوئے ہیں، پھر بھی امت کی عصری ضروریات سے پوری طرح آگاہ ہیں۔",
    history_q1_title: "مرکزی کیمپس کی بنیاد",
    history_q1_desc: "پہلا سنگ بنیاد اس دور کے معزز علماء اور روشن خیالوں نے رکھا تھا۔ ابتدائی جماعت صرف 15 سرشار طلباء پر مشتمل تھی جو مقدس علم کے متلاشی تھے۔",
    history_q2_title: "نصاب کی تشکیل",
    history_q2_desc: "روایتی درس نظامی کو جدید تدریسی فریم ورک کے ساتھ مربوط کرنے والا ایک سخت نصاب باضابطہ طور پر اپنایا گیا، جس نے اسلامی اداروں کے لیے ایک نیا معیار قائم کیا۔",
    history_q3_title: "عظیم کتب خانے کا افتتاح",
    history_q3_desc: "ہزاروں تاریخی جلدوں اور نایاب مخطوطات کو ذخیرہ کرنے والی وسیع لائبریری عوام اور دنیا بھر کے محققین کے لیے کھولی گئی۔",
    history_q4_title: "ڈیجیٹل تبدیلی اور عالمی رسائی",
    history_q4_desc: "آن لائن پروگرامز اور ورچوئل کلاس رومز کا آغاز، جس سے دنیا بھر کے طلباء کو ہماری معزز فیکلٹی سے فائدہ اٹھانے کا موقع ملا۔",
    history_quote: "\"ہم محض کتابیں نہیں پڑھاتے؛ ہم نبوی نور سے معمور ایسے کرداروں کو ڈھالنے کی کوشش کرتے ہیں، جو تاریک ترین اوقات میں بھی رہنمائی کر سکیں۔\"",
    history_quote_author: "— بانی شیخ",
    vision_title: "مقصد اور مشن",
    vision_the_vision: "مقصد",
    vision_the_vision_desc: "اسلامی اسکالرشپ کا ایک عالمی ستون بننا، الہی رہنمائی کو پھیلانا اور ایسے ذہنوں کی پرورش کرنا جو ابدی سچائی کو عصری چیلنجوں سے جوڑتے ہیں۔ ہم ایک ایسے معاشرے کا تصور کرتے ہیں جو ایسے افراد کے ذریعے تبدیل ہو جو نبوی خوبیوں کے زندہ مجسم کے طور پر کام کریں۔",
    vision_the_mission: "مشن",
    vision_the_mission_desc: "سخت تعلیمی نظم و ضبط، روحانی تربیت، اور مقدس نصوص کے تحفظ کے ذریعے دین کی گہری سمجھ پیدا کرنا۔ ہم ایک ایسا ماحول فراہم کرنے کے لیے پرعزم ہیں جہاں ایمان اور عقل مکمل ہم آہنگی میں ہوں۔",
    vision_core_values: "بنیادی اقدار",
    val1_title: "اخلاص",
    val1_desc: "تمام اعمال خالصتاً اللہ کی رضا کے لیے کرنا۔",
    val2_title: "ادب",
    val2_desc: "تمام معاملات میں بہترین آداب پیدا کرنا۔",
    val3_title: "تقویٰ",
    val3_desc: "خالق کی ہر وقت موجودگی کا احساس رکھنا۔",
    val4_title: "خدمت",
    val4_desc: "عاجزی اور گہری ہمدردی کے ساتھ انسانیت کی خدمت کرنا۔",
    val5_title: "احسان",
    val5_desc: "عبادت اور دنیاوی فرائض دونوں میں کمال کے لیے جدوجہد کرنا۔",
    val6_title: "سند",
    val6_desc: "علم کی منتقلی کے اٹوٹ سلسلے کو محفوظ رکھنا۔",
    prof_title: "ہمارے ممتاز اساتذہ",
    prof_subtitle: "نبوی وراثت کے وارثوں سے سیکھیں۔ ہمارے علماء گہری سیاق و سباق کی آگاہی کے ساتھ مل کر دہائیوں کا روایتی مطالعہ لاتے ہیں۔",
    prof1_role: "سربراہ علوم حدیث",
    prof2_role: "چیف آف فقہ اور فتویٰ",
    prof3_role: "تصوف اور روحانیت",
    prof4_role: "عربی بیان بازی",
    prof_exp_label: "تجربہ",
    prof_desc: "مقامی اور بین الاقوامی سطح پر ایک مشہور ماہر، جو طلباء کو عملی اطلاق پر نظر رکھتے ہوئے بنیادی نصوص پر عبور دلانے کے لیے وقف ہیں۔",
    alumni_title: "عالمی سابق طلباء کا نیٹ ورک",
    alumni_subtitle: "داؤدیہ کے فارغ التحصیل دنیا بھر کی کمیونٹیز کو روشن کر رہے ہیں۔ کمیونٹی لیڈرز اور اماموں سے لے کر پیشہ ور افراد اور ماہرین تعلیم تک، ہمارے سابق طلباء جہاں بھی جاتے ہیں مقدس علم کی مشعل لے جاتے ہیں۔",
    stat1: "کل فارغ التحصیل",
    stat2: "رسائی والے ممالک",
    stat3: "شائع شدہ مصنفین",
    stat4: "فعال امام",
    alumni_contributions: "قابل ذکر خدمات",
    alumni_pioneer: "کمیونٹی پائنیر",
    alumni_class: "کلاس آف",
    alumni_desc: "ایک ترقی پذیر اندرونی شہر کے یوتھ سینٹر کا قیام جس میں روایتی اسلامی علوم کو مضبوط سماجی خدمات کے ساتھ ملایا گیا ہے، جس نے ہزاروں نوجوانوں کی زندگیوں پر گہرا اثر ڈالا ہے۔"
  }
};

Object.assign(en, newEn);
Object.assign(ta, newTa);
Object.assign(ur, newUr);

fs.writeFileSync(enFile, JSON.stringify(en, null, 2));
fs.writeFileSync(taFile, JSON.stringify(ta, null, 2));
fs.writeFileSync(urFile, JSON.stringify(ur, null, 2));

console.log("JSON updated successfully!");
